language: php

notifications:
  email:
    on_success: never

php:
  - 7.1
  - 7.2

matrix:
  fast_finish: true
  include:
    - php: 7.1

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install -n

script:
  - vendor/bin/phpunit

after_success:
  - travis_retry php vendor/bin/coveralls